services:
  mysql:
    image: mysql:8.4
    restart: always
    container_name: mysql-nlw
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports: 
      - '3336:3306'
    networks: 
      - nlw-network
networks:
  nlw-network:
    driver: bridge
